% test estimate_point_set_normals

clc;

addpath(genpath('../src'));
addpath('../data');


filenames = {'torus';...             
             'bowser';...
             'vase';...
             'kitten';...
             'spiky_cell_like_surface_light';...
             'sinico';...
             'bowser_MD';...
             'bunny_16k';...             
             };

fid = 1;
filename = strcat(cell2mat(filenames(fid,1)),'.mat');         
load(filename);

nb_ngb = 4; % >= 4 and adapt function of point set local density 
N = estimate_point_set_normals(P,nb_ngb); % normalized and oriented by default
plot_point_set_normals(P,N);